//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent2020 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent2020.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLL.LLLLL.LLLL.LL.L.LLLLLLLLLLLLLLLLLLLLLLLLLL.LLLLLLLLLLLLLL
        ///LLLLLLLLLL.LLLLLL.L.LLLLLLL.LLLLL.LLLLL.LLLL.LLLLLLLLLLLLL..LLLLLLLLLLLLLLLL.LLLLL.LLLLLLLL
        ///LLLLLLLLLLLLLLLLLLLLLLLLLLL..L.LLLLLLLLLLLLLLL.LL.LLLLLLLLL.LLLLLLLLL.LLLLLL.LLLLLLLL.LLLLL
        ///LLLLLLLLLL.LL..LLLL.LLLLLLL.LLLLLLLLLLL.LLLLLLLLLLL.LLLLLLLLLLLLLLLLL.LLLLLL.LLLLL.LLLLLLLL
        ///LLLLLLLLLL.LLLLLLLL.LLLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLL.LLLLLL.LLLL..LLLLLLLL
        ///LL.L..L.L..L.LL..L.....LLLL..L.L.LL..L...LLLLLL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11Values {
            get {
                return ResourceManager.GetString("Day11Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W5
        ///N3
        ///W4
        ///F2
        ///N3
        ///R180
        ///E2
        ///S4
        ///E5
        ///N4
        ///E2
        ///L90
        ///F81
        ///E5
        ///R180
        ///E2
        ///F88
        ///L90
        ///N4
        ///E1
        ///F90
        ///S3
        ///W3
        ///R90
        ///F80
        ///E4
        ///F28
        ///R180
        ///S1
        ///F80
        ///E4
        ///F18
        ///S5
        ///W4
        ///F13
        ///R90
        ///S3
        ///W5
        ///N2
        ///F76
        ///L90
        ///N4
        ///F49
        ///L180
        ///E5
        ///R90
        ///F51
        ///E4
        ///L180
        ///F86
        ///S5
        ///L180
        ///F3
        ///E5
        ///W1
        ///R90
        ///F54
        ///N4
        ///E5
        ///R90
        ///E4
        ///N3
        ///W1
        ///E4
        ///R180
        ///W2
        ///F2
        ///S5
        ///W4
        ///E3
        ///R90
        ///F49
        ///R90
        ///W5
        ///N3
        ///F47
        ///E1
        ///L90
        ///E2
        ///F86
        ///E3
        ///R90
        ///F100
        ///F84
        ///N2
        ///F12
        ///L90
        ///N4
        ///W5
        ///F40
        ///N5
        ///F68
        ///W3
        ///R90
        ///W4
        ///N1
        ///F63
        ///W5
        ///S3
        ///F52
        ///R180
        ///W1
        ///W4
        ///L90
        ///N4
        ///R90
        ///S4
        ///L90
        ///F77
        ///R90
        ///E5
        ///F20
        ///N3
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day12Values {
            get {
                return ResourceManager.GetString("Day12Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1695
        ///1157
        ///1484
        ///1717
        ///622
        ///1513
        ///1924
        ///63
        ///1461
        ///1971
        ///1382
        ///1587
        ///1913
        ///1665
        ///1464
        ///1914
        ///1637
        ///1527
        ///1424
        ///1361
        ///1187
        ///272
        ///1909
        ///1448
        ///1623
        ///1164
        ///1931
        ///1646
        ///1096
        ///1655
        ///1962
        ///1961
        ///1694
        ///1792
        ///1989
        ///1616
        ///138
        ///1887
        ///1357
        ///1965
        ///1085
        ///308
        ///2007
        ///1254
        ///1179
        ///1124
        ///1719
        ///1467
        ///1928
        ///1630
        ///1676
        ///1359
        ///1241
        ///1511
        ///1413
        ///1656
        ///1818
        ///1919
        ///1422
        ///1745
        ///1208
        ///1609
        ///1544
        ///1775
        ///1154
        ///1057
        ///1440
        ///1242
        ///1202
        ///1266
        ///1305
        ///1836
        ///1760
        ///1730
        ///1396
        ///1315
        ///1496
        ///1964
        ///1300
        ///1195
        ///1583
        ///1607
        ///1743
        ///1682
        ///1453
        ///1848
        ///13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Values {
            get {
                return ResourceManager.GetString("Day1Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-5 r: rrrjr
        ///9-10 x: pxcbpxxwkqjttx
        ///8-13 b: rjbbbbvgrbrfjx
        ///3-5 d: dtddsdddddsddddddwd
        ///3-11 q: qbqsqqzqqxkmbqx
        ///3-4 v: vgvhcvxlbfcwg
        ///1-7 t: rtctmtt
        ///8-11 s: ksssswsssstssssss
        ///2-6 v: vxvvvlvv
        ///16-18 c: ptgprcccvqvbfcnckc
        ///18-20 w: wgtnwgnwvzwqhqtwvwrw
        ///14-18 k: kkkkkkxkkkkkknkkkl
        ///3-6 f: pwfgqlbbrfvwf
        ///6-10 h: pqlfbhcnglgvhdgddn
        ///2-13 k: bkfdvztsdkkkwm
        ///8-12 d: dddddddddddd
        ///1-10 v: lvvvvvvvvvvnvvvvvv
        ///2-3 d: dfdz
        ///3-10 w: vwwwwwnwwwwwxww
        ///2-7 c: ccwkpggxd
        ///4-5 g: kgqqg
        ///1-14 q: bcqqqqqqdqqqqbqqcq
        ///1-10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Values {
            get {
                return ResourceManager.GetString("Day2Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#.....#..#..#....##.........#.
        ///...#...#.........#..#.#..#.....
        ///#.#...#.#....#.....#..#..##..##
        ///..#..#.#.#.....#..#..#..##.....
        ///.#..........#....####..##.#..#.
        ///....##.......#.#.....#.........
        ///....#......#....####.#.##......
        ///........##..........##......#..
        ///.........#........##..#.#.....#
        ///.#..##..........#..#...#..##.#.
        ///........#........#.....#....#.#
        ///..#.......#.###...#.......##...
        ///.##..##.#...#........#.........
        ///...#....#..#..#..##.......#..#.
        ///.#.#.##.##..##..#.#.....#.....#
        ///....#.........#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3Values {
            get {
                return ResourceManager.GetString("Day3Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ecl:#eef340 eyr:2023 hcl:#c0946f pid:244684338 iyr:2020 cid:57 byr:1969 hgt:152cm
        ///
        ///pid:303807545 cid:213 ecl:gry hcl:#fffffd
        ///eyr:2038 byr:1951
        ///hgt:171cm iyr:2011
        ///
        ///hcl:#c0946f byr:1933 eyr:2025 pid:517067213 hgt:173cm
        ///ecl:hzl
        ///iyr:2018
        ///
        ///pid:5253256652 byr:2009 hgt:152cm iyr:1989 eyr:1968 hcl:64cb63 ecl:hzl
        ///
        ///iyr:2013
        ///pid:862607211 eyr:2020
        ///hgt:174cm
        ///byr:1990
        ///ecl:blu hcl:#888785
        ///
        ///ecl:grn byr:1955
        ///pid:608098408 eyr:2027 iyr:2020 hcl:#b6652a cid:264
        ///hgt:181cm
        ///
        ///byr:1998 ecl:hzl eyr:2021
        ///hcl: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Values {
            get {
                return ResourceManager.GetString("Day4Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBFFFFBRLL
        ///BFBBBBFLLL
        ///FBBBFBFLLR
        ///BFBBBFBLRR
        ///FBBFFBFLRR
        ///FFBFFBFRRR
        ///FBFBBBBLLL
        ///BFFBFFFRLR
        ///BFFBFFFRLL
        ///BFBBFBFRRL
        ///FBFFFFBLRR
        ///BBFFBFBLLR
        ///BBFBFFBRLR
        ///BFBFBFFRLR
        ///FBFFBFBRRL
        ///BFFFFBFRLR
        ///FFBBBBBRLR
        ///BFFFBFBLLR
        ///FBBBBBBRLL
        ///FBBFBFBRRL
        ///FBFBFBFLRL
        ///FFBFBBFRLL
        ///BFBFFBFRRL
        ///FBBBBFBLLR
        ///FFBBFBFLRR
        ///BFBFBBFRRL
        ///FBFFFBBLLR
        ///FBBFFBFRRR
        ///FFFBFBBLRL
        ///FBBBBFBRRL
        ///BFBFBBFLRL
        ///BBFFBFBLRL
        ///BBFFFFFLRL
        ///BBFBBFFRLR
        ///FFBFBBBRRL
        ///FBFFFFFRLR
        ///FFFBBFFLRR
        ///BFFFBFFLRL
        ///BFBFFFBRLR
        ///BBFBFBFLRR
        ///FBBBBFFRRR
        ///FBFFFBFRLL
        ///FBFFFFFL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5Values {
            get {
                return ResourceManager.GetString("Day5Values", resourceCulture);
            }
        }
    }
}
